server:
  # 禁用 Spring 生成404等错误信息，返回到前台
  error:
    whitelabel:
      enabled: false
  port: 8083
  tomcat:
    uri-encoding: UTF-8
  #servlet:
    #context-path: /gatewayZuul
    
# zuul相关配置     
zuul:
  # 所有头信息都传递到后台服务（注意：默认cookie是不传递到后台服务的，如果这样配不行就把*去掉，直接配个属性放到这里就行）
  sensitive-headers:
    "*"
  # 禁止访问某些地址（可以使用通配符的方式配置，比如*代表一层，**代表多层）
  ignored-patterns:
    /product/config_test
  # 自定义路由规则（注：下面的配置是将/testProduct/**路由到product服务上去（就是可以使用/testProduct访问product服务））
  routes:
    # 规则名称（可以随便写）
    testProduct:
      path: /testProduct/**
      service-id: product
    # 上面配置的简洁写法（服务名称:路由规则）  
    #product: /testProduct/**
      
spring:
  # JSON相关配置
  jackson:
    locale: zh_CN
    default-property-inclusion: non-null
