server:
  # 禁用 Spring 生成404等错误信息，返回到前台
  error:
    whitelabel:
      enabled: false
  port: 8083
  tomcat:
    uri-encoding: UTF-8
  #servlet:
    #context-path: /gatewayZuul
    
# zuul相关配置     
zuul:
  # 自定义路由规则（注：下面的配置是将/testProduct/**路由到product服务上去（就是可以使用/testProduct访问product服务））
  routes:
    # 规则名称（可以随便写）
    testProduct:
      path: /testProduct/**
      service-id: product
      
spring:
  # JSON相关配置
  jackson:
    locale: zh_CN
    default-property-inclusion: non-null
