server:
  # 禁用 Spring 生成404等错误信息，返回到前台
  error:
    whitelabel:
      enabled: false
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  #servlet:
    #context-path: /order
spring:
  # JSON相关配置
  jackson:
    locale: zh_CN
    default-property-inclusion: non-null
    
  # JPA相关配置  
  jpa:
    database: mysql
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none   
                      
# 配置 PRODUCT 服务的负载均衡策略（注意：product是服务的名称，可通过eureka管理端查看到）          
PRODUCT:
  ribbon:
    # 具体负载均衡实现类（可自定义）
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
