spring:
  # 数据源相关配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.229.132:3306/springcloud_demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: Jiang@123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      # 测试连接是否有效的查询语句
      connection-test-query: select 1
              
  # RabbitMQ相关配置（注意：我们这里面配置MQ的原因是Spring Cloud Bus要使用，它的配置刷新就是通过MQ来做的）
  rabbitmq:
    addresses: 192.168.229.132:5672
    username: guest
    password: guest
    virtual-host: /  
    
  # Spring Cloud Bus 配置Config自动刷新  
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true   
        
# 断路器相关配置（注：更多配置和配置的的意思可以查看HystrixController类）
management:
  endpoint:
    hystrix:
      stream:
        # 开启监控
        enabled: true
      config:
        execution:
          isolation:
            thread: 
              timeoutInMilliseconds: 2000        
          
# 日志级别相关      
logging:
  level:
    org.springframework.cloud.netflix.feign: debug
    com.firecode.elktest.biz.dao: debug
    org.hibernate.SQL: debug
    
# 开启全局debug日志    
#debug: true

config_test: 我是测试配置自动刷新的1212
