server:
  # 禁用 Spring 生成404等错误信息，返回到前台
  error:
    whitelabel:
      enabled: false
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  #servlet:
    #context-path: /product
spring:
  application:
    name: product
  # JSON相关配置
  jackson:
    locale: zh_CN
    default-property-inclusion: non-null
  # 数据源相关配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.229.132:3306/springcloud_demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: Jiang@123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      # 测试连接是否有效的查询语句
      connection-test-query: select 1
  # JPA相关配置  
  jpa:
    database: mysql
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none      
# 日志级别相关      
logging:
  level:
    com.firecode.elktest.biz.dao: debug
    org.hibernate.SQL: debug
# 开启全局debug日志    
#debug: true
